name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: echo "Trigger Jenkins Job"
      - run: curl -I -u ${{ secrets.JENKINS_USERNAME }}:${{ secrets.JENKINS_PASSWORD }} http://192.168.1.120:8080/job/test1/build?token=test1
#       - name: Jenkins trigger jon
#         uses: jabbukka/jenkins-trigger@main
#         with:
#           url: "http://192.168.1.120"
#           user_name: "jenkinsuser1"
#           api_token: "11f2c3b8b9c1cff806c6f672049d696d87"
#           job_name: "test1"
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event"
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner"
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}"
